### ISSUE TITLE
Beta4 release does not run X86 tests out of the box

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/net462-pluggable-agent#37]
I installed TestCentric.GuiRunner 2.0.0-beta4 via "choco install testcentric-gui --pre" and opened it via "testcentric".
My tests are not being loaded, and I get the exception:
--Win32Exceptionsystem cannot find the file specified
  at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
  at TestCentric.Engine.Services.TestAgency.GetAgent(TestPackage package) in C:\Users\charlie\dev\TestCentric\testcentric-engine\src\TestEngine\testcentric.engine\Services\TestAgency.cs:line 153
  at TestCentric.Engine.Services.TestAgentService.GetAgent(TestPackage package) in C:\Users\charlie\dev\TestCentric\testcentric-engine\src\TestEngine\testcentric.engine\Services\TestAgentService.cs:line 81
  at TestCentric.Engine.Runners.AssemblyRunner.CreateAgentAndRunnerIfNeeded() in C:\Users\charlie\dev\TestCentric\testcentric-engine\src\TestEngine\testcentric.engine\Runners\AssemblyRunner.cs:line 236
  at TestCentric.Engine.Runners.AssemblyRunner.Explore(TestFilter filter) in C:\Users\charlie\dev\TestCentric\testcentric-engine\src\TestEngine\testcentric.engine\Runners\AssemblyRunner.cs:line 45

Is there a package missing in chocolatery?
I uninstalled the pre-release and installed 1.6.4. With 1.6.4 I was able to load my tests.

Furthermore, is possible to run NUnit4 tests with the current testcentric version?

**Comment by CharliePoole** [comment]
It turns out that the Net462PluggableAgent, which is bundled with the GUI, doesn't include the X86 agent, even though we build and test it!!! So when you try to do something that requires it an exception is thrown. On the positive side, this should mean that I only have to do a bug fix in the agent, which you can then install separately.

**Comment by CharliePoole** [comment]
@MartinZec I created a new build of the agent and also added tests in both the agent project and the gui. It looks good to me, but it would be best if you can install and test the agent before I do a 2.4.1 release. 

You can install the  dev  build using

`choco install TestCentric.Extension.Net462PluggableAgent --version 2.4.1-dev00008 --source https://www.myget.org/F/testcentric/api/v2`

**Comment by CharliePoole** [comment]
@MartinZec Sorry, my bad. Should have said

`choco install testcentric-extension-net462-pluggable=agent --version 2.4.1-dev00008 --source https://www.myget.org/F/testcentric/api/v2`

But they each have the same binaries anyway, so I'll take that as solved and release 2.4.1 today.
